AWSTemplateFormatVersion: '2010-09-09'

Description:
  Create VPC Only.
  [Usage]
    aws cloudformation create-stack --stack-name <cfm-unique-name> --parameters ParameterKey=ArgsVpcName,ParameterValue=<Vpc-Name> --template-body file://setup01-vpc.yml
  [Example]
    cd <this yaml file path>
    aws cloudformation create-stack --stack-name cfm-test1 --parameters ParameterKey=ArgsVpcName,ParameterValue=Vpc-Test1 --template-body file://setup01-vpc.yml
    aws cloudformation delete-stack --stack-name cfm-test1

Parameters:
  ArgsVpcPrefixName:
    Type: String
    Description: VPC tag args CLI.
    Default: default

Mappings:
  StackConfig:
    VPC:
      CIDR: 10.0.0.0/16

Resources:
  #common
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap
        - StackConfig
        - VPC
        - CIDR
      Tags:
        - Key: Name
          Value: !Sub
            - "${ArgsVpcPrefixName}-vpc"
            - { ArgsVpcPrefixName: !Ref ArgsVpcPrefixName }

Outputs:
  VPCId:
    Value: !Ref MainVPC
    Export:
      Name: !Sub "${AWS::StackName}-vpc"
