AWSTemplateFormatVersion: '2010-09-09'
#
# [Description:]
#   Create VPC Only.
#  [Usage]
#    aws cloudformation create-stack 
#      --template-body file://setup01-vpc.yml
#      --stack-name <unique-stack-name> 
#      --parameters 
#      ParameterKey=ArgProjectName,ParameterValue=<project-name> 
#      ParameterKey=ArgVpcCidr,ParameterValue=<cidr> 
#  [Example]
#    ---Initialize setting
#    cd <this yaml file path>
#    export AWS_DEFAULT_PROFILE=<profile_name>
#    unset AWS_CFSTACK_ARGS_VPC
#    export AWS_CFSTACK_ARGS_VPC=$(cat << EOM
#    --template-body file://setup01-vpc.yml 
#    --stack-name cf-simplesvr1-01vpn 
#    --parameters 
#    ParameterKey=ArgProjectName,ParameterValue=prj-simplesvr1 
#    ParameterKey=ArgVpcCidr,ParameterValue=10.0.0.0/16 
#    EOM
#    )
#    echo $AWS_CFSTACK_ARGS_VPC
#
#    ---When validation template
#    aws cloudformation validate-template --template-body file://setup01-vpc.yml
#
#    ---When create stack
#    aws cloudformation create-stack $AWS_CFSTACK_ARGS_VPC
#
#    ---When delete stack
#    aws cloudformation delete-stack --stack-name cf-simplesvr1-01vpn 
#
Description:
  CloudFormation Template

Parameters:
  ArgProjectName:
    Type: String
    Default: "prj-default"
    AllowedPattern: "[0-9a-zA-Z\\-]*"
  ArgVpcCidr:
    Type: String
    Default: "172.16.0.0/16"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ArgVpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 
            - "${prjname}-vpc"
            - { prjname: !Ref ArgProjectName }

Outputs:
  ExportParamVpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub 
            - "Export-${prjname}-VpcId"
            - { prjname: !Ref ArgProjectName }
